export const researchCards = [
    {id: 1, image: "/images/cardImages/research/r1.png", title: "Algorithms to Localize Food Contamination Events in Blockchain-based Trusted Food Supply Chains ", text: "Enhancing the traceability of the food supply chain is important for food system safety and security. However, existing tracing mechanisms for the food supply chain are costly and inefficient. In this chapter, we discuss how blockchain-based ledgers are now being introduced to improve traceability. "},
    {id: 2, image: "/images/cardImages/research/r2.png", title: "Blockchain and the Scientific Method ", text: "The basic distributed ledger technology underpinning cryptocurrencies has recently been used in domains as diverse as shipping, political elections, food safety, and health record management, where transactions are immutably posted to the ledger with a time stamp. In this work, we discuss how ills of science may be ameliorated by pre-registering hypotheses and posting data, analyses, and results on a public blockchain. "},
    {id: 3, image: "/images/cardImages/research/r3.png", title: "Building Formally Verified Performant Blockchain Systems", text: "Work in the groups of Madhusudan Parthasarathy and Indranil Gupta has focused on building formally verified performant blockchain systems, where properties related to consensus and integrity are formally guaranteed."},
    {id: 4, image: "/images/cardImages/research/r4.png", title: "Case Uses for Blockchain in the Smallholder Agricultural Sector in Sub-Saharan Africa", text: "Blockchain technology has the potential to reduce the need for trust and to ensure accountability and equity in smallholder agricultural development. Our research presents two applications, one already in progress and one hypothetical, using blockchain to address market failures in the smallholder sector in Sub-Saharan Africa. "},
    {id: 5, image: "/images/cardImages/research/r5.png", title: "HyperService: Interoperability and Programmability Across Heterogeneous Blockchains", text: "HyperService aims to allow interoperability and programmability across heterogeneous blockchains, powered by two innovative designs: (i) a developer-facing programming framework and (ii) a secure blockchain-facing cryptography protocol that provably realizes those applications on blockchains. "},
    {id: 6, image: "/images/cardImages/research/r6.png", title: "Improving Robustness of Secure Multiparty Computation", text: "Current deployment of MPC in the real world faces several challenges, including costs (computation, bandwidth, latency), network delays, and output delivery guarantees. Our current research is focusing on how some of the recent techniques developed in the synchronous MPC literature can be used to optimize the asymptotic costs in the offline phase of asynchronous MPC protocols."},
    {id: 7, image: "/images/cardImages/research/r7.png", title: "Information-Theoretic Approaches to Scalable Blockchain Systems and Distributed Trust", text: "In this chapter, we take a few blockchain applications as examples and highlight the storage and communication demands for maintaining a full node in the network. We then study approaches with roots in coding theory that aim to reduce this cost and enable network scaling. Finally, we study practical use cases in establishing distributed trust in computational systems using coding-theoretic methods."},
    {id: 8, image: "/images/cardImages/research/r8.png", title: "Understanding the Drivers of the Crypto Token Market", text: "Using a state-of-the-art machine learning method for nature language processing to analyze large volume of twitter data, combined with large volume of time series trading data, the study provides empirical evidence that the token market is driven by speculative trading in the short term but the community is drawn by the intrinsic value of the tokens, such as the technology, team, vision, and product underlying these crypto tokens. "}
];
